<a href="https://colab.research.google.com/github/Rubnserrano/DataScience/blob/main/00_curso_tensorflow_certificate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EJERCICIOS


00.  TensorFlow Fundamentals Exercises
01.  Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
02.  Find the shape, rank and size of the tensors you created in 1.
03.  Create two tensors containing random values between 0 and 1 with shape [5, 300].
04.  Multiply the two tensors you created in 3 using matrix multiplication.
05.  Multiply the two tensors you created in 3 using dot product.
06.  Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
0.7  Find the min and max values of the tensor you created in 6 along the first axis.
0.8  Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
0.9  Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
0.10 One-hot encode the tensor you created in 9.

In [9]:
2#
shape1 = scalar.shape
rank1 = scalar.ndim
size1 = tf.size(scalar).numpy()
print(f'Shape, Rank, Size of a scalar = {shape1, rank1, size1}')

shape2 = vector.shape
rank2 = vector.ndim
size2 = tf.size(vector).numpy()
print(f'Shape, Rank, Size of a vector = {shape2, rank2, size2}')

shape3 = matrix.shape
rank3= matrix.ndim
size3 = tf.size(matrix).numpy()
print(f'Shape, Rank, Size of a matrix = {shape3, rank3, size3}')




Shape, Rank, Size of a scalar = (TensorShape([]), 0, 1)
Shape, Rank, Size of a vector = (TensorShape([2]), 1, 2)
Shape, Rank, Size of a matrix = (TensorShape([3, 3]), 2, 9)


In [6]:
#1
import tensorflow as tf
scalar = tf.constant(8)
vector = tf.constant([9,9])
matrix = tf.constant([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                       [[10,11,12],
                       [13,14,15]]])

print(scalar)
print(vector)
print(matrix)
print(tensor)

tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor([9 9], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]], shape=(2, 2, 3), dtype=int32)
